- id: "1712615457521"
  alias: Open door notification
  description: Send notification when a door is opened
  trigger:
    - type: opened
      platform: device
      device_id: 9fc907dc8d33e9014ce3c84b403dbc8e
      entity_id: 7869814d7349a434137aee7ccb86dcdf
      domain: binary_sensor
    - type: opened
      platform: device
      device_id: 51ae4a15022e68d022df57b6da7876ae
      entity_id: 0096705ba6c964f1ac76e7b8296199c9
      domain: binary_sensor
    - type: opened
      platform: device
      device_id: ed6e309b9e1ee6ea23e8279a8105e54f
      entity_id: f6b30763d5fda8a4d0a36f00702831e1
      domain: binary_sensor
  condition:
    - condition: device
      device_id: 08e82d3a8211d249742b9697050557ca
      domain: device_tracker
      entity_id: 00a03a286bc9472f94402cb92731fd30
      type: is_not_home
  action:
    - service: notify.mobile_app_sm_s901b
      metadata: {}
      data:
        title: Door opened
        message:
          "{{ trigger.entity_id }}, Date: {{ now().strftime('%Y-%m-%d') }},
          Time: {{ now().strftime('%H:%M:%S') }}'"
        data:
          ttl: 0
          priority: high
  mode: single
- id: "1715862234975"
  alias: PVoutput
  description: Post solar power output to pvoutput.org every 5 minutes
  trigger:
    - platform: time_pattern
      minutes: "5"
  condition:
    - condition: numeric_state
      entity_id: sensor.growatt_inputpower
      above: 0
  action:
    - service: rest_command.update_pvoutput
      data: {}
  mode: single
- id: "1715986630410"
  alias: Living Room Cube face-based control
  description: Control Living Room devices with Aqara Cube
  use_blueprint:
    path: rvaidya/aqara_magic_cube.yaml
    input:
      remote: 732e88904629cafa6725df2c902ed953
      active_face: input_number.aqara_cube_last_activated_face
      one_to_one:
        - type: toggle
          device_id: d124ae33ab3287f1e294480e0ac45236
          entity_id: f5aeb4306985900cc361cd5b38d0f9dd
          domain: light
      slide_any_side: false
      two_to_two:
        - service: media_player.media_play_pause
          metadata: {}
          data: {}
          target:
            device_id: ba337df91115b719aa417cd27aeb62b0
      rotate_left_side_1:
        - device_id: d124ae33ab3287f1e294480e0ac45236
          domain: light
          entity_id: f5aeb4306985900cc361cd5b38d0f9dd
          type: brightness_decrease
      rotate_right_side_1:
        - device_id: d124ae33ab3287f1e294480e0ac45236
          domain: light
          entity_id: f5aeb4306985900cc361cd5b38d0f9dd
          type: brightness_increase
      five_to_five:
        - service: media_player.media_play_pause
          metadata: {}
          data: {}
          target:
            device_id: ba337df91115b719aa417cd27aeb62b0
      rotate_left_side_5:
        - service: media_player.media_previous_track
          target:
            device_id:
              - ba337df91115b719aa417cd27aeb62b0
          data: {}
      rotate_right_side_5:
        - service: media_player.media_next_track
          target:
            device_id:
              - ba337df91115b719aa417cd27aeb62b0
          data: {}
      rotate_right_side_3:
        - service: media_player.volume_up
          target:
            device_id: ba337df91115b719aa417cd27aeb62b0
          data: {}
      rotate_left_side_3:
        - service: media_player.volume_down
          target:
            device_id:
              - ba337df91115b719aa417cd27aeb62b0
          data: {}
      three_to_three:
        - service: media_player.volume_mute
          target:
            device_id:
              - ba337df91115b719aa417cd27aeb62b0
          data:
            is_volume_muted: true
      four_to_four:
        - type: toggle
          device_id: d124ae33ab3287f1e294480e0ac45236
          entity_id: f5aeb4306985900cc361cd5b38d0f9dd
          domain: light
      six_to_six:
        - service: media_player.volume_mute
          target:
            device_id:
              - ba337df91115b719aa417cd27aeb62b0
          data:
            is_volume_muted: true
      rotate_left_side_2:
        - service: media_player.media_previous_track
          target:
            device_id:
              - ba337df91115b719aa417cd27aeb62b0
          data: {}
      rotate_left_side_4:
        - device_id: d124ae33ab3287f1e294480e0ac45236
          domain: light
          entity_id: f5aeb4306985900cc361cd5b38d0f9dd
          type: brightness_decrease
      rotate_left_side_6:
        - service: media_player.volume_down
          target:
            device_id:
              - ba337df91115b719aa417cd27aeb62b0
          data: {}
      rotate_right_side_2:
        - service: media_player.media_next_track
          target:
            device_id:
              - ba337df91115b719aa417cd27aeb62b0
          data: {}
      rotate_right_side_4:
        - device_id: d124ae33ab3287f1e294480e0ac45236
          domain: light
          entity_id: f5aeb4306985900cc361cd5b38d0f9dd
          type: brightness_increase
      rotate_right_side_6:
        - service: media_player.volume_up
          target:
            device_id: ba337df91115b719aa417cd27aeb62b0
          data: {}
- id: "1717101940680"
  alias: Doorbell
  description: ""
  trigger:
    - type: occupied
      platform: device
      device_id: 08bb8e0167e171210fbb2360c16e0c4c
      entity_id: 9292ffaca4dbf1501b8aa19df0492caa
      domain: binary_sensor
  condition: []
  action:
    - service: siren.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: siren.kichen_siren_play_tone
    - service: notify.mobile_app_sm_s901b
      data:
        message: Someone is at the front door
        data:
          ttl: 0
          priority: high
    - service: notify.mobile_app_sm_g970f
      data:
        message: Someone is at the front door
        data:
          ttl: 0
          priority: high
    - service: notify.mobile_app_galaxy_tab
      data:
        message: Someone is at the front door
        data:
          ttl: 0
          priority: high
    - service: notify.lg_oled_tv
      data:
        message: Someone is at the front door
        data:
          icon: /home/homeassistant/images/doorbell.png
  mode: single
- id: "1717183076711"
  alias: Close curtains on sunset
  description: ""
  trigger:
    - platform: sun
      event: sunset
      offset: 0
  condition: []
  action:
    - device_id: ad6695b6357acd3e5545e0d43e4b55c3
      domain: cover
      entity_id: 533bba4afb502dc1d1c37606690b5ad6
      type: close
  mode: single
- id: "1717424745811"
  alias: "Office switch: open curtains"
  description: ""
  trigger:
    - platform: device
      device_id: 233bc83db575dac2d0d5eb61d32c735c
      domain: zwave_js
      type: event.value_notification.central_scene
      property: scene
      property_key: "004"
      endpoint: 0
      command_class: 91
      subtype: Endpoint 0 Scene 004
      value: 0
  condition:
    - condition: device
      device_id: ad6695b6357acd3e5545e0d43e4b55c3
      domain: cover
      entity_id: 533bba4afb502dc1d1c37606690b5ad6
      type: is_closed
  action:
    - device_id: ad6695b6357acd3e5545e0d43e4b55c3
      domain: cover
      entity_id: 533bba4afb502dc1d1c37606690b5ad6
      type: open
  mode: single
- id: "1717424823777"
  alias: "Office switch: close curtains"
  description: ""
  trigger:
    - platform: device
      device_id: 233bc83db575dac2d0d5eb61d32c735c
      domain: zwave_js
      type: event.value_notification.central_scene
      property: scene
      property_key: "003"
      endpoint: 0
      command_class: 91
      subtype: Endpoint 0 Scene 003
      value: 0
  condition:
    - condition: device
      device_id: ad6695b6357acd3e5545e0d43e4b55c3
      domain: cover
      entity_id: 533bba4afb502dc1d1c37606690b5ad6
      type: is_open
  action:
    - device_id: ad6695b6357acd3e5545e0d43e4b55c3
      domain: cover
      entity_id: 533bba4afb502dc1d1c37606690b5ad6
      type: close
  mode: single
- id: "1717446926717"
  alias: Turn on living room TV
  description: Turn On Living Room TV with WakeOnLan
  trigger:
    - platform: device
      device_id: ba337df91115b719aa417cd27aeb62b0
      domain: webostv
      type: webostv.turn_on
  condition: []
  action:
    - service: wake_on_lan.send_magic_packet
      data:
        mac: b0:37:95:1a:11:8a
  mode: single
- id: "1717939911692"
  alias: Basement Auto Light
  description: Turn on Basement Light when Basement Motion is detected
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.basement_motion_motion
      light_target:
        area_id: basement
      no_motion_wait: 60
