- id: "1712615457521"
  alias: Open door notification
  description: Send notification when a door is opened
  trigger:
    - type: opened
      platform: device
      device_id: 9fc907dc8d33e9014ce3c84b403dbc8e
      entity_id: 7869814d7349a434137aee7ccb86dcdf
      domain: binary_sensor
    - type: opened
      platform: device
      device_id: 51ae4a15022e68d022df57b6da7876ae
      entity_id: 0096705ba6c964f1ac76e7b8296199c9
      domain: binary_sensor
    - type: opened
      platform: device
      device_id: ed6e309b9e1ee6ea23e8279a8105e54f
      entity_id: f6b30763d5fda8a4d0a36f00702831e1
      domain: binary_sensor
  condition:
    - condition: device
      device_id: 08e82d3a8211d249742b9697050557ca
      domain: device_tracker
      entity_id: 00a03a286bc9472f94402cb92731fd30
      type: is_not_home
  action:
    - service: notify.mobile_app_sm_s901b
      metadata: {}
      data:
        title: Door opened
        message:
          "{{ trigger.entity_id }}, Date: {{ now().strftime('%Y-%m-%d') }},
          Time: {{ now().strftime('%H:%M:%S') }}'"
        data:
          ttl: 0
          priority: high
  mode: single
- id: "1715986630410"
  alias: Living Room Cube face-based control
  description: Control Living Room devices with Aqara Cube
  use_blueprint:
    path: rvaidya/aqara_magic_cube.yaml
    input:
      remote: 732e88904629cafa6725df2c902ed953
      active_face: input_number.aqara_cube_last_activated_face
      one_to_one:
        - type: toggle
          device_id: d124ae33ab3287f1e294480e0ac45236
          entity_id: f5aeb4306985900cc361cd5b38d0f9dd
          domain: light
      slide_any_side: false
      two_to_two:
        - service: media_player.media_play_pause
          metadata: {}
          data: {}
          target:
            device_id: ba337df91115b719aa417cd27aeb62b0
      rotate_left_side_1:
        - device_id: d124ae33ab3287f1e294480e0ac45236
          domain: light
          entity_id: f5aeb4306985900cc361cd5b38d0f9dd
          type: brightness_decrease
      rotate_right_side_1:
        - device_id: d124ae33ab3287f1e294480e0ac45236
          domain: light
          entity_id: f5aeb4306985900cc361cd5b38d0f9dd
          type: brightness_increase
      five_to_five:
        - service: media_player.media_play_pause
          metadata: {}
          data: {}
          target:
            device_id: ba337df91115b719aa417cd27aeb62b0
      rotate_left_side_5:
        - service: media_player.media_previous_track
          target:
            device_id:
              - ba337df91115b719aa417cd27aeb62b0
          data: {}
      rotate_right_side_5:
        - service: media_player.media_next_track
          target:
            device_id:
              - ba337df91115b719aa417cd27aeb62b0
          data: {}
      rotate_right_side_3:
        - service: media_player.volume_up
          target:
            device_id: ba337df91115b719aa417cd27aeb62b0
          data: {}
      rotate_left_side_3:
        - service: media_player.volume_down
          target:
            device_id:
              - ba337df91115b719aa417cd27aeb62b0
          data: {}
      three_to_three:
        - service: media_player.volume_mute
          target:
            device_id:
              - ba337df91115b719aa417cd27aeb62b0
          data:
            is_volume_muted: true
      four_to_four:
        - type: toggle
          device_id: d124ae33ab3287f1e294480e0ac45236
          entity_id: f5aeb4306985900cc361cd5b38d0f9dd
          domain: light
      six_to_six:
        - service: media_player.volume_mute
          target:
            device_id:
              - ba337df91115b719aa417cd27aeb62b0
          data:
            is_volume_muted: true
      rotate_left_side_2:
        - service: media_player.media_previous_track
          target:
            device_id:
              - ba337df91115b719aa417cd27aeb62b0
          data: {}
      rotate_left_side_4:
        - device_id: d124ae33ab3287f1e294480e0ac45236
          domain: light
          entity_id: f5aeb4306985900cc361cd5b38d0f9dd
          type: brightness_decrease
      rotate_left_side_6:
        - service: media_player.volume_down
          target:
            device_id:
              - ba337df91115b719aa417cd27aeb62b0
          data: {}
      rotate_right_side_2:
        - service: media_player.media_next_track
          target:
            device_id:
              - ba337df91115b719aa417cd27aeb62b0
          data: {}
      rotate_right_side_4:
        - device_id: d124ae33ab3287f1e294480e0ac45236
          domain: light
          entity_id: f5aeb4306985900cc361cd5b38d0f9dd
          type: brightness_increase
      rotate_right_side_6:
        - service: media_player.volume_up
          target:
            device_id: ba337df91115b719aa417cd27aeb62b0
          data: {}
