- id: "1712615457521"
  alias: Open door notification
  description: Send notification when a door is opened
  trigger:
    - type: opened
      platform: device
      device_id: 118ce1941d4e6e1c22c43dbd00cb808e
      entity_id: 7869814d7349a434137aee7ccb86dcdf
      domain: binary_sensor
    - type: opened
      platform: device
      device_id: 51eba2dd60daafcc2611bfac107f0a31
      entity_id: fb7fbe04e160bf11ab9c0dbe6257b2c7
      domain: binary_sensor
    - type: opened
      platform: device
      device_id: 3dbd7ad9cc1ea49a2c10227fd8d7854a
      entity_id: 0096705ba6c964f1ac76e7b8296199c9
      domain: binary_sensor
  condition:
    - condition: device
      device_id: 93bb9cc2c571926bfbcc747d50237b45
      domain: device_tracker
      entity_id: 00a03a286bc9472f94402cb92731fd30
      type: is_not_home
  action:
    - service: notify.mobile_app_sm_s901b
      metadata: {}
      data:
        title: Door opened
        message:
          "{{ trigger.entity_id }}, Date: {{ now().strftime('%Y-%m-%d') }},
          Time: {{ now().strftime('%H:%M:%S') }}'"
        data:
          ttl: 0
          priority: high
  mode: single
- id: "1715862234975"
  alias: PVoutput
  description: Post solar power output to pvoutput.org every 5 minutes
  trigger:
    - platform: time_pattern
      minutes: "5"
  condition:
    - condition: numeric_state
      entity_id: sensor.growatt_inputpower
      above: 0
  action:
    - service: rest_command.update_pvoutput
      data: {}
  mode: single
- id: "1715986630410"
  alias: Living Room Cube face-based control
  description: Control Living Room devices with Aqara Cube
  use_blueprint:
    path: rvaidya/aqara_magic_cube.yaml
    input:
      remote: 102f4daa5c5b8899963b4ae9986998ef
      active_face: input_number.aqara_cube_last_activated_face
      one_to_one:
        - type: toggle
          device_id: ce8c1ddb8e57dfd64442f197ca0c1b67
          entity_id: f5aeb4306985900cc361cd5b38d0f9dd
          domain: light
      slide_any_side: false
      two_to_two:
        - service: media_player.media_play_pause
          metadata: {}
          data: {}
          target:
            device_id:
              - 6bb780a1b238a8f164a25f6b6c881732
      rotate_left_side_1:
        - device_id: ce8c1ddb8e57dfd64442f197ca0c1b67
          domain: light
          entity_id: f5aeb4306985900cc361cd5b38d0f9dd
          type: brightness_decrease
      rotate_right_side_1:
        - device_id: ce8c1ddb8e57dfd64442f197ca0c1b67
          domain: light
          entity_id: f5aeb4306985900cc361cd5b38d0f9dd
          type: brightness_increase
      five_to_five:
        - service: media_player.media_play_pause
          metadata: {}
          data: {}
          target:
            device_id:
              - 6bb780a1b238a8f164a25f6b6c881732
      rotate_left_side_5:
        - service: media_player.media_previous_track
          target:
            device_id:
              - 6bb780a1b238a8f164a25f6b6c881732
          data: {}
      rotate_right_side_5:
        - service: media_player.media_next_track
          target:
            device_id:
              - 6bb780a1b238a8f164a25f6b6c881732
          data: {}
      rotate_right_side_3:
        - service: media_player.volume_up
          target:
            device_id:
              - 6bb780a1b238a8f164a25f6b6c881732
              - d6852b90354af73e87e7be7f58203262
          data: {}
      rotate_left_side_3:
        - service: media_player.volume_down
          target:
            device_id:
              - 6bb780a1b238a8f164a25f6b6c881732
              - d6852b90354af73e87e7be7f58203262
          data: {}
      three_to_three:
        - service: media_player.volume_mute
          target:
            device_id:
              - 6bb780a1b238a8f164a25f6b6c881732
          data:
            is_volume_muted: true
      four_to_four:
        - type: toggle
          device_id: ce8c1ddb8e57dfd64442f197ca0c1b67
          entity_id: f5aeb4306985900cc361cd5b38d0f9dd
          domain: light
      six_to_six:
        - service: media_player.volume_mute
          target:
            device_id:
              - 6bb780a1b238a8f164a25f6b6c881732
          data:
            is_volume_muted: true
      rotate_left_side_2:
        - service: media_player.media_previous_track
          target:
            device_id:
              - 6bb780a1b238a8f164a25f6b6c881732
          data: {}
      rotate_left_side_4:
        - device_id: ce8c1ddb8e57dfd64442f197ca0c1b67
          domain: light
          entity_id: f5aeb4306985900cc361cd5b38d0f9dd
          type: brightness_decrease
      rotate_left_side_6:
        - service: media_player.volume_down
          target:
            device_id:
              - 6bb780a1b238a8f164a25f6b6c881732
              - d6852b90354af73e87e7be7f58203262
          data: {}
      rotate_right_side_2:
        - service: media_player.media_next_track
          target:
            device_id:
              - 6bb780a1b238a8f164a25f6b6c881732
          data: {}
      rotate_right_side_4:
        - device_id: ce8c1ddb8e57dfd64442f197ca0c1b67
          domain: light
          entity_id: f5aeb4306985900cc361cd5b38d0f9dd
          type: brightness_increase
      rotate_right_side_6:
        - service: media_player.volume_up
          target:
            device_id:
              - 6bb780a1b238a8f164a25f6b6c881732
              - d6852b90354af73e87e7be7f58203262
          data: {}
- id: "1717101940680"
  alias: Doorbell
  description: ""
  trigger:
    - type: occupied
      platform: device
      device_id: e619c22ee731ba11a006681b0e19301b
      entity_id: 9292ffaca4dbf1501b8aa19df0492caa
      domain: binary_sensor
  condition: []
  action:
    - service: siren.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: siren.kichen_siren_play_tone
    - service: notify.mobile_app_sm_s901b
      data:
        message: Someone is at the front door
        data:
          ttl: 0
          priority: high
    - service: notify.mobile_app_sm_g970f
      data:
        message: Someone is at the front door
        data:
          ttl: 0
          priority: high
    - service: notify.mobile_app_galaxy_tab
      data:
        message: Someone is at the front door
        data:
          ttl: 0
          priority: high
    - service: notify.lg_oled_tv
      data:
        message: Someone is at the front door
        data:
          icon: /home/homeassistant/images/doorbell.png
  mode: single
- id: "1717183076711"
  alias: Close curtains on sunset
  description: ""
  trigger:
    - platform: sun
      event: sunset
      offset: 0
  condition: []
  action:
    - device_id: 75777aee4992dfd7fefbb79520c629bc
      domain: cover
      entity_id: d1bdf03dc63ef5a1bbc725b9bf560fe9
      type: close
  mode: single
- id: "1717424745811"
  alias: "Office switch: open curtains"
  description: ""
  trigger:
    - platform: device
      device_id: f620bd40ab0a3299c0b46162b86aac7d
      domain: zwave_js
      type: event.value_notification.central_scene
      property: scene
      property_key: "004"
      endpoint: 0
      command_class: 91
      subtype: Endpoint 0 Scene 004
      value: 0
  condition:
    - condition: not
      conditions:
        - condition: device
          device_id: 75777aee4992dfd7fefbb79520c629bc
          domain: cover
          entity_id: d1bdf03dc63ef5a1bbc725b9bf560fe9
          type: is_open
  action:
    - device_id: 75777aee4992dfd7fefbb79520c629bc
      domain: cover
      entity_id: d1bdf03dc63ef5a1bbc725b9bf560fe9
      type: open
  mode: single
- id: "1717424823777"
  alias: "Office switch: close curtains"
  description: ""
  trigger:
    - platform: device
      device_id: f620bd40ab0a3299c0b46162b86aac7d
      domain: zwave_js
      type: event.value_notification.central_scene
      property: scene
      property_key: "003"
      endpoint: 0
      command_class: 91
      subtype: Endpoint 0 Scene 003
      value: 0
  condition:
    - condition: not
      conditions:
        - condition: device
          device_id: 75777aee4992dfd7fefbb79520c629bc
          domain: cover
          entity_id: d1bdf03dc63ef5a1bbc725b9bf560fe9
          type: is_closed
  action:
    - device_id: 75777aee4992dfd7fefbb79520c629bc
      domain: cover
      entity_id: d1bdf03dc63ef5a1bbc725b9bf560fe9
      type: close
  mode: single
- id: "1717446926717"
  alias: Turn on living room TV
  description: Turn On Living Room TV with WakeOnLan
  trigger:
    - platform: device
      device_id: 6bb780a1b238a8f164a25f6b6c881732
      domain: webostv
      type: webostv.turn_on
  condition: []
  action:
    - service: wake_on_lan.send_magic_packet
      data:
        mac: b0:37:95:1a:11:8a
  mode: single
- id: "1717939911692"
  alias: Basement Auto Light
  description: Turn on Basement Light when Basement Motion is detected
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.basement_motion_motion
      light_target:
        area_id: basement
      no_motion_wait: 60
- id: "1718196868013"
  alias: Toilet Auto Light
  description: ""
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.toilet_multisensor_motion_detection
      light_target:
        entity_id: light.toilet_light_light
      no_motion_wait: 90
- id: "1718200676292"
  alias: Front Yard Auto Light
  description:
    Turn on front yard light if it's dark outside and someone is approaching
    the front door.
  use_blueprint:
    path: custom/motion_light_w_conditions.yaml
    input:
      motion_entity: binary_sensor.g4_doorbell_motion
      light_target:
        entity_id: light.front_yard_light_light
      additional_conditions:
        - condition: or
          conditions:
            - condition: sun
              before: sunrise
            - condition: sun
              after: sunset
- id: "1718215095435"
  alias: "Office switch: toggle front light"
  description: ""
  trigger:
    - platform: device
      device_id: f620bd40ab0a3299c0b46162b86aac7d
      domain: zwave_js
      type: event.value_notification.central_scene
      property: scene
      property_key: "002"
      endpoint: 0
      command_class: 91
      subtype: Endpoint 0 Scene 002
      value: 0
  condition: []
  action:
    - type: toggle
      device_id: 1ca8e922258f21814e3dc50869663e30
      entity_id: 7b7f713bdab95eccdb1c6988ecb441c4
      domain: light
  mode: single
- id: "1718218472644"
  alias: Hallway Auto Lights triggered by Front Door
  description: ""
  trigger:
    - type: opened
      platform: device
      device_id: 118ce1941d4e6e1c22c43dbd00cb808e
      entity_id: 7869814d7349a434137aee7ccb86dcdf
      domain: binary_sensor
  condition: []
  action:
    - service: automation.trigger
      metadata: {}
      data:
        skip_condition: true
      target:
        entity_id: automation.hallway_auto_lights
  mode: single
- id: "1718455866890"
  alias: Smallway Auto Light
  description: Turn on Smallway Light when Smallway Motion is detected
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.smallway_motion_motion
      light_target:
        entity_id: light.smallway_light_switch
      no_motion_wait: 0
- id: "1718473101835"
  alias: Basement Auto Light triggered by Garage Door
  description: ""
  trigger:
    - type: opened
      platform: device
      device_id: 51eba2dd60daafcc2611bfac107f0a31
      entity_id: fb7fbe04e160bf11ab9c0dbe6257b2c7
      domain: binary_sensor
  condition: []
  action:
    - service: automation.trigger
      metadata: {}
      data:
        skip_condition: true
      target:
        entity_id: automation.basement_auto_light
  mode: single
- id: "1718474653669"
  alias: Hallway Auto Lights
  description: ""
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.hallway_motion_motion
      light_target:
        device_id: 3ac4907cb0b4ad72f1fd6153b75e9cc8
      no_motion_wait: 60
- id: "1718477092437"
  alias: Hallway Lights toggled by Hallway Switch
  description: ""
  trigger:
    - platform: device
      type: changed_states
      device_id: 17d5bd308ecc8a23a4a8b36ba47fb585
      entity_id: bd5b1f03d01b0979a6c92338a2a13717
      domain: switch
  condition: []
  action:
    - type: toggle
      device_id: 3ac4907cb0b4ad72f1fd6153b75e9cc8
      entity_id: 2f59f824e761191a665688ac274bf57f
      domain: light
  mode: single
- id: "1718752490414"
  alias: Towel Warmer enable in the morning
  description: ""
  trigger:
    - platform: time
      at: 07:00:00
  condition: []
  action:
    - type: turn_on
      device_id: 464da44378e18ac7a0f135d0101529b1
      entity_id: b3dfb2ab8d9fc27211ddfc0af4318b4f
      domain: switch
  mode: single
- id: "1718752536845"
  alias: Towel Warmer disable in the evening
  description: ""
  trigger:
    - platform: time
      at: "21:00:00"
  condition: []
  action:
    - type: turn_off
      device_id: 464da44378e18ac7a0f135d0101529b1
      entity_id: b3dfb2ab8d9fc27211ddfc0af4318b4f
      domain: switch
  mode: single
- id: "1718814525340"
  alias: Kitchen Bench Lights toggled by Unknown Kitchen North Switch
  description: ""
  trigger:
    - platform: device
      type: changed_states
      device_id: 10a91df9e250ac37f97ce8f735f2724e
      entity_id: a1f4909bddb03ba63e716bbb54ceaeb4
      domain: switch
  condition: []
  action:
    - type: toggle
      device_id: 1cdd6fa955db8cd544aa569a5573e766
      entity_id: 34c02e482d0dc7c3f05bcd68f6d89b3e
      domain: light
  mode: single
- id: "1718825185048"
  alias: Kitchen table lights are toggled by Unknown Kitchen South Switch
  description: ""
  trigger:
    - platform: device
      type: changed_states
      device_id: 52464dc1991cc4cd33614cf3b2ab4d14
      entity_id: 17249d76d4b0fdc55ff81821ec64d920
      domain: switch
  condition: []
  action:
    - type: toggle
      device_id: a68d41b27b097a44f9381f27fe16924e
      entity_id: f2e33f387ae03429b0c8abaeb21ec111
      domain: light
  mode: single
- id: "1718825566036"
  alias: Back Yard Auto Light
  description:
    Turn on front yard light if it's dark outside and someone is approaching
    the front door.
  use_blueprint:
    path: custom/motion_light_w_conditions.yaml
    input:
      motion_entity: binary_sensor.g5_flex_motion
      light_target:
        entity_id: light.back_yard_light_switch
      additional_conditions:
        - condition: or
          conditions:
            - condition: sun
              before: sunrise
            - condition: sun
              after: sunset
- id: "1720697453857"
  alias: Office Front Light toggled by Office Back Switch Bottom
  description: ""
  trigger:
    - platform: device
      type: changed_states
      device_id: 17d5bd308ecc8a23a4a8b36ba47fb585
      entity_id: 26cfcd4be57fc22dee261d4901bd5dd3
      domain: switch
  condition: []
  action:
    - type: toggle
      device_id: 1ca8e922258f21814e3dc50869663e30
      entity_id: 7b7f713bdab95eccdb1c6988ecb441c4
      domain: light
  mode: single
- id: "1720697593635"
  alias: Office Back Light toggled by Office Back Switch Top
  description: ""
  trigger:
    - platform: device
      type: changed_states
      device_id: 8493ad33d9f7917e0a42e1fb5725f9ef
      entity_id: 9569f469aabaf4700b24d6e83f8b5ee9
      domain: switch
  condition: []
  action:
    - type: toggle
      device_id: c4b6030b936448bbad3cb047d7990df8
      entity_id: 13125dfd884c1ddcc1969c54e2970e5e
      domain: light
  mode: single
- id: "1720697694856"
  alias: Office Front Light toggled by Hallway Switch Left
  description: ""
  trigger:
    - platform: device
      type: changed_states
      device_id: 8493ad33d9f7917e0a42e1fb5725f9ef
      entity_id: 4b4f0386927eeed0ac7f46e0499a4302
      domain: switch
  condition: []
  action:
    - type: toggle
      device_id: 1ca8e922258f21814e3dc50869663e30
      entity_id: 7b7f713bdab95eccdb1c6988ecb441c4
      domain: light
  mode: single
- id: "1720718449190"
  alias: "Office switch: toggle back light"
  description: ""
  trigger:
    - platform: device
      device_id: f620bd40ab0a3299c0b46162b86aac7d
      domain: zwave_js
      type: event.value_notification.central_scene
      property: scene
      property_key: "001"
      endpoint: 0
      command_class: 91
      subtype: Endpoint 0 Scene 001
      value: 0
  condition: []
  action:
    - type: toggle
      device_id: c4b6030b936448bbad3cb047d7990df8
      entity_id: 13125dfd884c1ddcc1969c54e2970e5e
      domain: light
  mode: single
- id: "1721164596666"
  alias: Wash machine done notification
  description:
    Send notification when wash machine goes from on to standby (i.e. finishes
    a cycle).
  trigger:
    - platform: state
      entity_id:
        - sensor.wash_machine_state
      from: "on"
      to: standby
      for:
        hours: 0
        minutes: 1
        seconds: 0
  condition: []
  action:
    - service: notify.mobile_app_galaxy_tab
      data:
        data:
          ttl: 0
          priority: high
        message: Wash machine done!
    - service: notify.mobile_app_sm_s901b
      data:
        data:
          ttl: 0
          priority: high
        message: Wash machine done!
    - service: notify.mobile_app_sm_g970f
      data:
        data:
          ttl: 0
          priority: high
        message: Wash machine done!
  mode: single
- id: "1722207820068"
  alias: Notify when CO2 sensors go crazy
  description: Send notification when any CO2 sensor shows a value above 1500.
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.ep1_co2
        - sensor.itho_office_co2
        - sensor.itho_bedroom_co2
        - sensor.itho_kitchen_co2
        - sensor.living_room_carbon_dioxide
        - sensor.airthings_kitchen_carbon_dioxide
      above: 1500
  condition: []
  action:
    - service: notify.mobile_app_sm_s901b
      metadata: {}
      data:
        title: Crazy CO2
        message:
          "{{ trigger.entity_id }} > {{ trigger.above}}, When: {{ now().strftime('%Y-%m-%d
          %H:%M:%S') }}, for {{ trigger.for }}"
        data:
          ttl: 0
          priority: high
  mode: single
- id: "1722208826933"
  alias: Notify when to disable bypass valve
  description: "Send notification when supplied air is warmer than exhausted air. "
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.esphome_web_10c200_43063_supply_temperature_to_inside
      above: sensor.esphome_web_10c200_43073_exhaust_temperature_from_inside
      for:
        hours: 0
        minutes: 3
        seconds: 0
  condition:
    - condition: state
      entity_id: switch.esphome_web_10c200_bypass_valve
      state: "on"
  action:
    - service: notify.mobile_app_sm_s901b
      metadata: {}
      data:
        title: Disable bypass?
        message: Supply air is warmer than exhaust
        data:
          ttl: 0
          priority: high
  mode: single
- id: "1722209272117"
  alias: Notify when to enable bypass valve
  description:
    "Send notification when air from outside is being warned up by the
    heat exchanger. "
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.esphome_web_10c200_43063_supply_temperature_to_inside
      above: sensor.esphome_web_10c200_43033_supply_temperature_from_outside
      for:
        hours: 0
        minutes: 3
        seconds: 0
  condition:
    - condition: state
      entity_id: switch.esphome_web_10c200_bypass_valve
      state: "off"
  action:
    - service: notify.mobile_app_sm_s901b
      metadata: {}
      data:
        title: Enable bypass?
        message: Supplied air is warmer than outside
        data:
          ttl: 0
          priority: high
  mode: single
