substitutions:
  name: "epone-office"
  friendly_name: Everything Presence One Office w/CO2
packages:
  Everything_Smart_Technology.Everything_Presence_One: github://everythingsmarthome/everything-presence-one/everything-presence-one-sen0609-ble-co2.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
ota:
  - platform: esphome
api:
  encryption:
    key: XqfzeM+qCz/3SQXPGBM46pDYtavGNOwG1EqYsUwh+jQ=

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
