substitutions:
  name: esphome-web-5c9be4
  friendly_name: Atom S3 Lite in Master Bedroom

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  platformio_options:
    board_build.flash_mode: dio
  project:
    name: esphome.web
    version: '1.0'
  includes:
    - ble-node.h
  libraries:
    - "h2zero/NimBLE-Arduino"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  # Set up a wifi access point
  ap: {}

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

dashboard_import:
  package_import_url: github://esphome/firmware/esphome-web/esp32s3.yaml@main
  import_full_config: true

# To have a "next url" for improv serial
web_server:

mqtt:
  broker: 192.168.1.107
  username: !secret mqtt_user
  password: !secret mqtt_password
  discovery: true

custom_component:
- lambda: |-
    auto my_node = new BleNodeComponent("master_bedroom");
    return {my_node};

time:
  - platform: homeassistant
    id: homeassistant_time

bluetooth_proxy: