substitutions:
  name: everything-presence-lite-60c2b8
  friendly_name: Everything Presence Lite 60c2b8
packages:
  EverythingSmartTechnology.Everything_Presence_Lite: github://everythingsmarthome/everything-presence-lite/everything-presence-lite-ha.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: 0ThkloAsE6SrifB7/iGMN/UMOFBxsRG8Veavy0C1yRs=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
